import { Planet } from '../models/planet';

const planets = [
  new Planet(1, 'Tatooine'),
  new Planet(2, 'Alderaan'),
  new Planet(3, 'Yavin IV'),
  new Planet(4, 'Hoth'),
  new Planet(5, 'Dagobah'),
  new Planet(6, 'Bespin'),
  new Planet(7, 'Endor'),
  new Planet(8, 'Naboo'),
  new Planet(9, 'Coruscant'),
  new Planet(10, 'Kamino'),
  new Planet(11, 'Geonosis'),
  new Planet(12, 'Utapau'),
  new Planet(13, 'Mustafar'),
  new Planet(14, 'Kashyyyk'),
  new Planet(15, 'Polis Massa'),
  new Planet(16, 'Mygeeto'),
  new Planet(17, 'Felucia'),
  new Planet(18, 'Cato Neimoidia'),
  new Planet(19, 'Saleucami'),
  new Planet(20, 'Stewjon'),
  new Planet(21, 'Eriadu'),
  new Planet(21, 'Corellia'),
  new Planet(23, 'Rodia'),
  new Planet(24, 'Nal Hutta'),
  new Planet(25, 'Dantooine'),
  new Planet(26, 'Bestine IV'),
  new Planet(27, 'Ord Mantell'),
  new Planet(28, 'unknown'),
  new Planet(29, 'Trandosha'),
  new Planet(30, 'Socorro'),
  new Planet(31, 'Mon Cala'),
  new Planet(32, 'Chandrila'),
  new Planet(33, 'Sullust'),
  new Planet(34, 'Toydaria'),
  new Planet(35, 'Malastare'),
  new Planet(36, 'Dathomir'),
  new Planet(37, 'Ryloth'),
  new Planet(38, 'Aleen Minor'),
  new Planet(39, 'Vulpter'),
  new Planet(40, 'Troiken'),
  new Planet(41, 'Tund'),
  new Planet(42, 'Haruun Kal'),
  new Planet(43, 'Cerea'),
  new Planet(44, 'Glee Anselm'),
  new Planet(45, 'Iridonia'),
  new Planet(46, 'Tholoth'),
  new Planet(47, 'Iktotch'),
  new Planet(48, 'Quermia'),
  new Planet(49, 'Dorin'),
  new Planet(50, 'Champala'),
  new Planet(51, 'Mirial'),
  new Planet(52, 'Serenno'),
  new Planet(53, 'Concord Dawn'),
  new Planet(54, 'Zolan'),
  new Planet(55, 'Ojom'),
  new Planet(56, 'Skako'),
  new Planet(57, 'Muunilinst'),
  new Planet(58, 'Shili'),
  new Planet(59, 'Kalee'),
  new Planet(60, 'Umbara'),
  new Planet(61, 'Jakku'),

  new Planet(101, 'Vallt'),
  new Planet(102, 'Fest'),
  new Planet(103, 'Onderon'),
  new Planet(104, 'Jedha'),
  new Planet(105, 'Grange'),
  new Planet(106, 'Aria Prime'),
  new Planet(107, 'Lexrul'),
  new Planet(108, 'Arkanis'),

];

export function getPlanets() {
  return {
    count: planets.length,
    results: planets
  };
}
